Updated README with app level index routing
cloudfoundry-community/splunk-firehose-nozzle pull request #292
Opened 2021-09-24 11:09 UTC by harshit-splunk

2021-09-24 21:12 UTC, luckyj5 requested changes
Lets also add that "ADD_APP_INFO" (cache info) is required to be enabled for per app index routing feature. 
If Add-app-info is not enabled, nozzle will not have app's metadata which will include SPLUNK_INDEX value.

2021-09-24 21:15 UTC, luckyj5 requested changes

2021-09-24 21:15 UTC, luckyj5 commented on README.md
> +cf set-env <APP_NAME> SPLUNK_INDEX <ENV_VAR_VALUE>
I think for this, if you set-env via CLI, you still need to restage the application for those updated envs to take effect. Please cross check. Thanks!

2021-09-27 05:44 UTC, harshit-splunk commented on README.md
> +cf set-env <APP_NAME> SPLUNK_INDEX <ENV_VAR_VALUE>
> I think for this, if you set-env via CLI, you still need to restage the application for those updated envs to take effect. Please cross check. Thanks!

In my testing, I was able to route data-gen events to the index provided using cf command. I tested following scenarios:
- deployed data_gen without setting SPLUNK_INDEX env variable and set env after it is deployed
- deployed data_gen with setting SPLUNK_INDEX env variable and update env with new index value
In both cases, event were ingested in newly specified index.

I think, if the app is using the environment variable then we are required to restage the application. For our use case, app doesn't rely on SPLUNK_INDEX, so no need to restage. Cloud controller endpoint will always returns latest env data. So as long as connector is invalidating app cache, it should be fine

2021-09-27 05:48 UTC, harshit-splunk commented
> Lets also add that "ADD_APP_INFO" (cache info) is required to be enabled for per app index routing feature.
> If Add-app-info is not enabled, nozzle will not have app's metadata which will include SPLUNK_INDEX value.

Sure

2021-09-28 17:33 UTC, luckyj5 commented
> > Lets also add that "ADD_APP_INFO" (cache info) is required to be enabled for per app index routing feature.
> > If Add-app-info is not enabled, nozzle will not have app's metadata which will include SPLUNK_INDEX value.
> 
> It doen't depend on ADD_APP_INFO config. As you can see in [router](https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/edd2401b7a787a1f59c19d619f07c4a258b11c68/eventrouter/default.go#L70), as long as event has app_id, it will call event.AnnotateWithAppData method. In event.AnnotateWithAppData method, it gets app information from cache from cf_app_id. If it find's SPLUNK_INDEX in app env, it'll add _info_splunk_index_ field in the event

ADD_APP_INFO config triggers nozzle to fetch cache info for apps. If it's not selected, then nozzle won't have cache info, which means it won't have env variables either. Let me know if it's otherwise.

2021-09-29 05:05 UTC, harshit-splunk commented
> > > Lets also add that "ADD_APP_INFO" (cache info) is required to be enabled for per app index routing feature.
> > > If Add-app-info is not enabled, nozzle will not have app's metadata which will include SPLUNK_INDEX value.
> > 
> > 
> > It doen't depend on ADD_APP_INFO config. As you can see in [router](https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/edd2401b7a787a1f59c19d619f07c4a258b11c68/eventrouter/default.go#L70), as long as event has app_id, it will call event.AnnotateWithAppData method. In event.AnnotateWithAppData method, it gets app information from cache from cf_app_id. If it find's SPLUNK_INDEX in app env, it'll add _info_splunk_index_ field in the event
> 
> ADD_APP_INFO config triggers nozzle to fetch cache info for apps. If it's not selected, then nozzle won't have cache info, which means it won't have env variables either. Let me know if it's otherwise.

On further analysis, found that boltdb cache is initialised only if ADD_APP_INFO is enabled otherwise NoCache is initialised. And app info will never be fetched from remote.
I'll make changes according to that.

2021-09-29 10:01 UTC, kashyap-splunk approved these changes

2021-09-29 17:57 UTC, luckyj5 commented on README.md
> +To enable per app index routing, you are required to set environmt variable `SPLUNK_INDEX`in your application and enable ADD_APP_INFO(Select at least one metadata) to enable app info caching. Make su
Please update as below: 

To enable per application index routing:
- Please set environment variable `SPLUNK_INDEX` in your application's manifest (example below - link to the example) 
- Make sure Splunk nozzle is configured with ADD_APP_INFO (Select at least one of AppName, OrgName/Id, SpaceName/id) to enable app info caching
- Make sure SPLUNK_INDEX specified in app's manifest exist in Splunk and can receive data for the configured Splunk HEC token.

2021-09-30 17:52 UTC, luckyj5 commented
Thanks for update @harshit-splunk. 
Just noticed this - [note](https://github.com/cloudfoundry-community/splunk-firehose-nozzle#please-note)
Please remove this as well.

2021-09-30 19:04 UTC, luckyj5 requested changes
Just noticed this - [note](https://github.com/cloudfoundry-community/splunk-firehose-nozzle#please-note) for SPLUNK_VERSION
Please remove this as well.

2021-10-01 21:00 UTC, luckyj5 approved these changes
LGTM

2021-10-01 21:00 UTC, merged