Add version info about VMware TAS in Readme
cloudfoundry-community/splunk-firehose-nozzle pull request #336
Opened 2023-01-11 12:15 UTC by vihas-splunk

2023-01-11 12:22 UTC, harshit-splunk requested changes

2023-01-16 04:50 UTC, harshit-splunk approved these changes

2023-01-16 04:53 UTC, harshit-splunk commented
@vihas-splunk can you make the functional tests pipeline green?

2023-01-16 09:18 UTC, vihas-splunk commented
> @vihas-splunk can you make the functional tests pipeline green?

Done

2023-01-16 09:22 UTC, merged